export const PHRASES = [
  { es: "¿Qué tal el día?", en: "How was your day?" },
  { es: "No te preocupes", en: "Don't worry" },
  { es: "Que tengas un buen día", en: "Have a good day" },
  { es: "Hasta pronto", en: "See you soon" },
  { es: "Claro que sí", en: "Of course / Yes, definitely" },
  { es: "A lo mejor", en: "Maybe / Perhaps" },
  { es: "Por supuesto", en: "Of course" },
  { es: "Me da igual", en: "I don't care / It's all the same to me" },
  { es: "Qué pena", en: "What a shame / How sad" },
  { es: "En serio?", en: "Seriously?" },
  { es: "No tengo ni idea", en: "I have no idea" },
  { es: "Cuídate", en: "Take care (informal)" },
  { es: "Disfruta", en: "Enjoy (informal)" },
  { es: "Buen provecho", en: "Enjoy your meal" },
  { es: "Qué aproveche", en: "Enjoy your meal" },
  { es: "Salud!", en: "Cheers! / Bless you! (after sneeze)" },
  { es: "Feliz fin de semana", en: "Happy weekend" },
];
