export const PHRASES = [
  { es: "Hola, ¿qué tal?", en: "Hello, how are you? (informal)" },
  { es: "Buenos días", en: "Good morning" },
  { es: "Buenas tardes", en: "Good afternoon / Good evening" },
  { es: "Buenas noches", en: "Good night" },
  { es: "¿Cómo estás?", en: "How are you? (informal)" },
  { es: "¿Cómo está usted?", en: "How are you? (formal)" },
  { es: "Muy bien, gracias. ¿Y tú?", en: "Very well, thank you. And you? (informal)" },
  { es: "Encantado/a", en: "Nice to meet you" },
  { es: "Mucho gusto", en: "Nice to meet you" },
  { es: "Hasta luego", en: "See you later" },
  { es: "Hasta mañana", en: "See you tomorrow" },
  { es: "Adiós", en: "Goodbye" },
  { es: "Por favor", en: "Please" },
  { es: "Gracias", en: "Thank you" },
  { es: "De nada", en: "You're welcome" },
  { es: "Lo siento", en: "I'm sorry" },
  { es: "Con permiso", en: "Excuse me (to pass)" },
  { es: "Perdón", en: "Excuse me / Sorry (for a mistake)" },
];
