export const PHRASES = [
  { es: "Me gusta este barrio.", en: "I like this neighborhood." },
  { es: "Me gusta caminar por la mañana.", en: "I like walking in the morning." },
  { es: "Me gusta cómo hablas español.", en: "I like how you speak Spanish." },
  { es: "Me gusta este café.", en: "I like this coffee." },
  { es: "Me gusta escuchar pódcasts en español.", en: "I like listening to podcasts in Spanish." },
  { es: "Me gusta esta canción.", en: "I like this song." },
  { es: "Me gusta llegar temprano.", en: "I like arriving early." },
  { es: "Me gusta pedir tortilla aquí.", en: "I like ordering omelet here." },

  { es: "Me gustan estas zapatillas.", en: "I like these sneakers." },
  { es: "Me gustan las películas españolas.", en: "I like Spanish movies." },
  { es: "Me gustan los mercados de barrio.", en: "I like local neighborhood markets." },
  { es: "Me gustan tus ideas.", en: "I like your ideas." },
  { es: "Me gustan esos libros.", en: "I like those books." },
  { es: "Me gustan las clases cortas.", en: "I like short classes." },

  { es: "¿Te gusta este restaurante?", en: "Do you like this restaurant?" },
  { es: "Te gusta vivir en el centro.", en: "You like living downtown." },
  { es: "¿Te gusta estudiar por la noche?", en: "Do you like studying at night?" },
  { es: "Te gusta ese pódcast, ¿verdad?", en: "You like that podcast, right?" },
  { es: "¿Te gustan las tapas?", en: "Do you like tapas?" },
  { es: "Te gustan los viajes largos.", en: "You like long trips." },
  { es: "¿Te gustan estas frases?", en: "Do you like these sentences?" },

  { es: "Le gusta trabajar desde casa.", en: "He likes working from home." },
  { es: "Le gusta este hotel.", en: "She likes this hotel." },
  { es: "Le gusta salir a correr.", en: "He likes going out for a run." },
  { es: "Le gusta comer tarde.", en: "She likes eating late." },
  { es: "Le gustan los perros grandes.", en: "He likes big dogs." },
  { es: "Le gustan esas gafas.", en: "She likes those glasses." },
  { es: "Le gusta la música en vivo.", en: "He likes live music." },

  { es: "Nos gusta este plan.", en: "We like this plan." },
  { es: "Nos gusta practicar todos los días.", en: "We like practicing every day." },
  { es: "Nos gusta hablar en español en casa.", en: "We like speaking in Spanish at home." },
  { es: "Nos gustan los menús del día.", en: "We like set lunch menus." },
  { es: "Nos gustan los barrios tranquilos.", en: "We like quiet neighborhoods." },
  { es: "Nos gusta llegar con tiempo.", en: "We like arriving with time to spare." },
  { es: "Nos gusta esta ciudad.", en: "We like this city." },

  { es: "Les gusta esta zona.", en: "They like this area." },
  { es: "Les gusta pedir para compartir.", en: "They like ordering food to share." },
  { es: "Les gusta madrugar.", en: "They like waking up early." },
  { es: "Les gusta ese bar.", en: "They like that bar." },
  { es: "Les gustan los museos gratis.", en: "They like free museums." },
  { es: "Les gustan los fines de semana tranquilos.", en: "They like calm weekends." },
  { es: "Les gusta aprender con audios.", en: "They like learning with audio." },
];
