export const PHRASES = [
  { es: "Cuando vivía en Sevilla, iba al trabajo en bici.", en: "When I lived in Seville, I used to go to work by bike." },
  { es: "Antes iba al gimnasio tres veces por semana.", en: "I used to go to the gym three times a week." },
  { es: "De niño, iba a casa de mis abuelos los domingos.", en: "As a child, I used to go to my grandparents house on Sundays." },
  { es: "En verano, iba a la playa cada tarde.", en: "In summer, I used to go to the beach every afternoon." },
  { es: "Siempre iba al mercado con mi madre.", en: "I always used to go to the market with my mother." },
  { es: "Cuando estudiaba, iba a la biblioteca después de clase.", en: "When I was studying, I used to go to the library after class." },
  { es: "Iba en autobús porque no tenía coche.", en: "I used to go by bus because I did not have a car." },
  { es: "Iba al centro para practicar español.", en: "I used to go downtown to practice Spanish." },
  { es: "Iba a correr antes de desayunar.", en: "I used to go running before breakfast." },
  { es: "Iba a esa cafetería casi todos los días.", en: "I used to go to that cafe almost every day." },

  { es: "Cuando era estudiante, tenía poco dinero.", en: "When I was a student, I had little money." },
  { es: "Antes tenía más tiempo libre.", en: "I used to have more free time." },
  { es: "Mi abuelo tenía un taller pequeño.", en: "My grandfather had a small workshop." },
  { es: "Cuando trabajaba allí, tenía turno de noche.", en: "When I worked there, I had the night shift." },
  { es: "Tenía una vecina muy simpática.", en: "I had a very nice neighbor." },
  { es: "En esa época tenía dos trabajos.", en: "At that time, I had two jobs." },
  { es: "Siempre tenía hambre después de clase.", en: "I was always hungry after class." },
  { es: "Tenía miedo de hablar en público.", en: "I was afraid of speaking in public." },
  { es: "De niño tenía el pelo más largo.", en: "As a child, I had longer hair." },
  { es: "Antes tenía que madrugar todos los días.", en: "Before, I had to wake up early every day." },

  { es: "En invierno hacía mucho frío.", en: "In winter, it used to be very cold." },
  { es: "Los domingos hacía paella con mi familia.", en: "On Sundays, I used to make paella with my family." },
  { es: "Cuando vivía fuera, hacía videollamadas cada noche.", en: "When I lived abroad, I used to make video calls every night." },
  { es: "Hacía los deberes después de cenar.", en: "I used to do homework after dinner." },
  { es: "En ese trabajo hacía horas extra.", en: "In that job, I used to work overtime." },
  { es: "Siempre hacía la compra los sábados.", en: "I always used to do grocery shopping on Saturdays." },
  { es: "Hacía ejercicio en casa.", en: "I used to exercise at home." },
  { es: "Mi madre hacía pan los fines de semana.", en: "My mother used to make bread on weekends." },
  { es: "Hacía fotos en todos los viajes.", en: "I used to take photos on every trip." },
  { es: "Cuando podía, hacía una siesta corta.", en: "When I could, I used to take a short nap." },

  { es: "La estación estaba siempre llena.", en: "The station was always crowded." },
  { es: "Mi oficina estaba cerca del río.", en: "My office was near the river." },
  { es: "Cuando llamabas, yo estaba en clase.", en: "When you called, I was in class." },
  { es: "El piso estaba en un cuarto sin ascensor.", en: "The apartment was on a fourth floor with no elevator." },
  { es: "Antes estaba más nervioso al hablar.", en: "Before, I was more nervous when speaking." },
  { es: "El bar estaba abierto hasta tarde.", en: "The bar used to be open late." },
  { es: "La comida estaba buenísima.", en: "The food was very good." },
  { es: "Mi hermano estaba en Londres ese año.", en: "My brother was in London that year." },
  { es: "Todo estaba más barato entonces.", en: "Everything was cheaper then." },
  { es: "La calle estaba vacía por la mañana.", en: "The street was empty in the morning." },
];
