export const PHRASES = [
  { es: "Voy a cocinar arroz esta noche.", en: "I am going to cook rice tonight." },
  { es: "Voy a salir del trabajo a las seis.", en: "I am going to leave work at six." },
  { es: "Voy a llamar a mi madre después.", en: "I am going to call my mother later." },
  { es: "Voy a estudiar una hora antes de dormir.", en: "I am going to study for an hour before sleeping." },
  { es: "Voy a pasar por tu casa en diez minutos.", en: "I am going to stop by your house in ten minutes." },
  { es: "Voy a pedir un café sin azúcar.", en: "I am going to order a coffee without sugar." },
  { es: "Voy a comprar billetes para el sábado.", en: "I am going to buy tickets for Saturday." },
  { es: "Voy a enviar el paquete hoy.", en: "I am going to send the package today." },
  { es: "Voy a cambiar de asiento.", en: "I am going to change seats." },
  { es: "Voy a quedarme en casa mañana.", en: "I am going to stay home tomorrow." },

  { es: "Vas a llegar tarde si no sales ya.", en: "You are going to be late if you do not leave now." },
  { es: "Vas a conocer a mi hermana hoy.", en: "You are going to meet my sister today." },
  { es: "Vas a necesitar efectivo en ese mercado.", en: "You are going to need cash in that market." },
  { es: "Vas a dormir mejor si apagas el móvil.", en: "You are going to sleep better if you turn off your phone." },
  { es: "Vas a repetir esta frase conmigo.", en: "You are going to repeat this sentence with me." },
  { es: "Vas a pedir la cuenta, ¿no?", en: "You are going to ask for the bill, right?" },
  { es: "Vas a coger el metro en Sol.", en: "You are going to take the metro at Sol." },

  { es: "Va a llover por la tarde.", en: "It is going to rain in the afternoon." },
  { es: "Va a empezar la reunión en cinco minutos.", en: "The meeting is going to start in five minutes." },
  { es: "Va a abrir una tienda nueva aquí.", en: "A new shop is going to open here." },
  { es: "Va a venir el técnico mañana.", en: "The technician is going to come tomorrow." },
  { es: "Va a subir el precio del alquiler.", en: "The rent price is going to go up." },
  { es: "Va a llamar el doctor esta tarde.", en: "The doctor is going to call this afternoon." },
  { es: "Va a cerrar el banco en media hora.", en: "The bank is going to close in half an hour." },

  { es: "Vamos a comer fuera hoy.", en: "We are going to eat out today." },
  { es: "Vamos a practicar estas frases otra vez.", en: "We are going to practice these sentences again." },
  { es: "Vamos a tomar el tren de las ocho.", en: "We are going to take the eight o'clock train." },
  { es: "Vamos a pedir una mesa junto a la ventana.", en: "We are going to ask for a table by the window." },
  { es: "Vamos a revisar tus notas.", en: "We are going to review your notes." },
  { es: "Vamos a quedar en la plaza.", en: "We are going to meet at the square." },
  { es: "Vamos a empezar desde el principio.", en: "We are going to start from the beginning." },

  { es: "Vais a llegar antes que nosotros.", en: "You all are going to arrive before us." },
  { es: "Vais a ver a Marta esta noche.", en: "You all are going to see Marta tonight." },
  { es: "Vais a necesitar chaqueta.", en: "You all are going to need a jacket." },
  { es: "Vais a coger el autobús veintisiete.", en: "You all are going to take bus twenty-seven." },
  { es: "Vais a repetir el diálogo dos veces.", en: "You all are going to repeat the dialogue twice." },

  { es: "Van a abrir la puerta ahora.", en: "They are going to open the door now." },
  { es: "Van a cancelar el vuelo por el viento.", en: "They are going to cancel the flight because of the wind." },
  { es: "Van a vender la casa este año.", en: "They are going to sell the house this year." },
  { es: "Van a entrevistar a tres candidatos.", en: "They are going to interview three candidates." },
  { es: "Van a pedir más tiempo.", en: "They are going to ask for more time." },
  { es: "Van a volver mañana por la mañana.", en: "They are going to come back tomorrow morning." },
];
