export const PHRASES = [
  { es: "¿Ves el mensaje? Lo veo ahora.", en: "Do you see the message? I see it now." },
  { es: "¿Tienes la llave? La tengo aquí.", en: "Do you have the key? I have it here." },
  { es: "¿Compraste el pan? Lo compré esta mañana.", en: "Did you buy the bread? I bought it this morning." },
  { es: "¿Reservaste la mesa? La reservé ayer.", en: "Did you reserve the table? I reserved it yesterday." },
  { es: "¿Conoces al nuevo jefe? Lo conozco de otra empresa.", en: "Do you know the new boss? I know him from another company." },
  { es: "¿Conoces a Marta? La conozco de la universidad.", en: "Do you know Marta? I know her from university." },
  { es: "¿Dónde está el contrato? Lo tengo en el correo.", en: "Where is the contract? I have it in my email." },
  { es: "¿Dónde está la factura? La tengo en PDF.", en: "Where is the invoice? I have it as a PDF." },
  { es: "Si veo a Carlos, lo llamo.", en: "If I see Carlos, I call him." },
  { es: "Si veo a Ana, la llamo.", en: "If I see Ana, I call her." },
  { es: "Cuando encuentro el libro, lo llevo.", en: "When I find the book, I bring it." },
  { es: "Cuando encuentro la tarjeta, la llevo.", en: "When I find the card, I bring it." },

  { es: "¿Tienes los documentos? Los tengo en la mochila.", en: "Do you have the documents? I have them in my backpack." },
  { es: "¿Compraste los billetes? Los compré anoche.", en: "Did you buy the tickets? I bought them last night." },
  { es: "¿Viste a tus primos? Los vi el sábado.", en: "Did you see your cousins? I saw them on Saturday." },
  { es: "¿Viste las fotos? Las vi ayer.", en: "Did you see the photos? I saw them yesterday." },
  { es: "Si encuentro las llaves, las traigo.", en: "If I find the keys, I bring them." },
  { es: "Si encuentro los audios, los envío.", en: "If I find the audio files, I send them." },
  { es: "¿Conoces a mis padres? Los conoces de la boda.", en: "Do you know my parents? You know them from the wedding." },
  { es: "¿Conoces las reglas? Las conozco bien.", en: "Do you know the rules? I know them well." },

  { es: "Le escribí a Laura esta mañana.", en: "I wrote to Laura this morning." },
  { es: "Le mandé un audio al profesor.", en: "I sent a voice note to the teacher." },
  { es: "Le dije la verdad a mi jefe.", en: "I told my boss the truth." },
  { es: "Le pedí ayuda al camarero.", en: "I asked the waiter for help." },
  { es: "Les envié los documentos a mis compañeros.", en: "I sent my coworkers the documents." },
  { es: "Les conté la noticia a mis padres.", en: "I told my parents the news." },
  { es: "Les expliqué el problema a mis vecinos.", en: "I explained the problem to my neighbors." },
  { es: "Les pedí una mesa a los camareros.", en: "I asked the waiters for a table." },
  { es: "¿Le puedes pasar este número a Marta?", en: "Can you pass this number to Marta?" },
  { es: "¿Les puedes confirmar la hora a tus amigos?", en: "Can you confirm the time to your friends?" },

  { es: "El informe para Marta: se lo envié ayer.", en: "The report for Marta: I sent it to her yesterday." },
  { es: "La dirección para Marta: se la mandé por WhatsApp.", en: "The address for Marta: I sent it to her by WhatsApp." },
  { es: "Los datos para Marta: se los pasé por correo.", en: "The details for Marta: I sent them to her by email." },
  { es: "Las fotos para Marta: se las enseñé anoche.", en: "The photos for Marta: I showed them to her last night." },
  { es: "El libro para ellos: se lo dejé en recepción.", en: "The book for them: I left it for them at reception." },
  { es: "La llave para ellos: se la di al portero.", en: "The key for them: I gave it to the doorman." },
  { es: "Los billetes para ellos: se los compré yo.", en: "The tickets for them: I bought them for them." },
  { es: "Las entradas para ellos: se las guardé.", en: "The passes for them: I kept them for them." },
  { es: "Cuando tenga el documento, se lo mando.", en: "When I have the document, I send it to them." },
  { es: "Cuando tenga las fotos, se las mando.", en: "When I have the photos, I send them to them." },
];
