export const PAST = [
  { es: "Ayer tuve que trabajar hasta muy tarde en la oficina.", en: "Yesterday I had to work until very late at the office." },
{ es: "Ayer tuve que estudiar hasta muy tarde en la biblioteca.", en: "Yesterday I had to study until very late at the library." },
{ es: "Ayer tuve que esperar dos horas en el aeropuerto.", en: "Yesterday I had to wait two hours at the airport." },
{ es: "Ayer tuve que limpiar toda la casa antes de la fiesta.", en: "Yesterday I had to clean the whole house before the party." },
{ es: "El lunes tuve que llevar mi coche al mecánico.", en: "On Monday I had to take my car to the mechanic." },
{ es: "El lunes tuve que ir al médico por la mañana.", en: "On Monday I had to go to the doctor in the morning." },
{ es: "Lo siento, pero ayer tuve un problema con mi teléfono.", en: "I am sorry, but yesterday I had a problem with my phone." },
{ es: "Lo siento, pero ayer tuve un problema con mi conexión a internet.", en: "I am sorry, but yesterday I had a problem with my internet connection." },
{ es: "Ella tuvo que salir temprano de la reunión.", en: "She had to leave the meeting early." },
{ es: "Ella tuvo que cancelar su viaje a Madrid.", en: "She had to cancel her trip to Madrid." },
{ es: "Él tuvo que pagar la cuenta en efectivo.", en: "He had to pay the bill in cash." },
{ es: "Él tuvo una buena idea para el nuevo proyecto.", en: "He had a good idea for the new project." },
{ es: "Mi hermano tuvo gripe la semana pasada.", en: "My brother had the flu last week." },
{ es: "Nosotros tuvimos que correr para coger el tren.", en: "We had to run to catch the train." },
{ es: "Nosotros tuvimos que cambiar nuestros planes a última hora.", en: "We had to change our plans at the last minute." },
{ es: "Nosotros tuvimos mucha suerte con el clima durante el viaje.", en: "We had a lot of luck with the weather during the trip." },
{ es: "¿Tuviste tiempo para leer el informe que te envié?", en: "Did you have time to read the report I sent you?" },
{ es: "¿Tuviste tiempo para cocinar la cena anoche?", en: "Did you have time to cook dinner last night?" },
{ es: "¿Por qué tuviste que ir al banco ayer?", en: "Why did you have to go to the bank yesterday?" },
{ es: "Ellos tuvieron que vender su casa el año pasado.", en: "They had to sell their house last year." },
{ es: "Ayer fui al supermercado para comprar leche y pan.", en: "Yesterday I went to the supermarket to buy milk and bread." },
{ es: "Ayer fui al mercado para comprar frutas y verduras.", en: "Yesterday I went to the market to buy fruits and vegetables." },
{ es: "Ayer fui a la farmacia a buscar medicina.", en: "Yesterday I went to the pharmacy to get medicine." },
{ es: "Ayer fui a la oficina de correos a enviar un paquete.", en: "Yesterday I went to the post office to send a package." },
{ es: "El verano pasado fui a España con mi familia.", en: "Last summer I went to Spain with my family." },
{ es: "El verano pasado fui a Italia con mis amigos.", en: "Last summer I went to Italy with my friends." },
{ es: "El domingo pasado fui al parque con mi perro.", en: "Last Sunday I went to the park with my dog." },
{ es: "El domingo pasado fui al cine con mi novia.", en: "Last Sunday I went to the movies with my girlfriend." },
{ es: "Ella fue a la playa todos los días de sus vacaciones.", en: "She went to the beach every day of her vacation." },
{ es: "Ella fue al gimnasio después de salir del trabajo.", en: "She went to the gym after leaving work." },
{ es: "Él fue a la fiesta pero no se quedó mucho tiempo.", en: "He went to the party but didn't stay very long." },
{ es: "Él fue a visitar a sus padres el fin de semana.", en: "He went to visit his parents on the weekend." },
{ es: "Nosotros fuimos a un restaurante japonés anoche.", en: "We went to a Japanese restaurant last night." },
{ es: "Nosotros fuimos a un bar nuevo en el centro.", en: "We went to a new bar in the center." },
{ es: "Nosotros fuimos a caminar por la montaña el sábado.", en: "We went to walk in the mountains on Saturday." },
{ es: "¿Fuiste a la reunión de equipo esta mañana?", en: "Did you go to the team meeting this morning?" },
{ es: "¿Fuiste al concierto el viernes por la noche?", en: "Did you go to the concert on Friday night?" },
{ es: "¿A dónde fuiste cuando saliste de la casa?", en: "Where did you go when you left the house?" },
{ es: "Ellos fueron al museo de historia natural ayer.", en: "They went to the natural history museum yesterday." },
{ es: "Ellos fueron a la boda de su mejor amigo.", en: "They went to their best friend's wedding." },
];
