export const PHRASES = [
  { es: "Puedo ayudarte con eso.", en: "I can help you with that." },
  { es: "Puedo hablar ahora cinco minutos.", en: "I can talk now for five minutes." },
  { es: "Puedo pasar a recogerte.", en: "I can stop by to pick you up." },
  { es: "Puedo pagar con tarjeta.", en: "I can pay by card." },
  { es: "Puedo quedarme un rato más.", en: "I can stay a little longer." },
  { es: "Puedo explicarlo otra vez.", en: "I can explain it again." },
  { es: "Puedo ir después de comer.", en: "I can go after lunch." },
  { es: "Puedo cambiarte el turno.", en: "I can switch your shift." },
  { es: "Puedo escuchar mejor con auriculares.", en: "I can hear better with headphones." },
  { es: "Puedo traerlo mañana.", en: "I can bring it tomorrow." },

  { es: "Puedes sentarte aquí.", en: "You can sit here." },
  { es: "Puedes abrir la ventana.", en: "You can open the window." },
  { es: "Puedes repetir más despacio.", en: "You can repeat more slowly." },
  { es: "Puedes usar mi bolígrafo.", en: "You can use my pen." },
  { es: "Puedes empezar cuando quieras.", en: "You can start whenever you want." },
  { es: "Puedes mandarme la ubicación.", en: "You can send me the location." },
  { es: "Puedes venir conmigo si quieres.", en: "You can come with me if you want." },

  { es: "Puede esperar en esta sala.", en: "You can wait in this room." },
  { es: "Puede dejar su maleta aquí.", en: "You can leave your suitcase here." },
  { es: "Puede pagar al final.", en: "You can pay at the end." },
  { es: "Puede venir sin cita.", en: "You can come without an appointment." },
  { es: "Puede entrar de uno en uno.", en: "You can enter one by one." },
  { es: "Puede tomar este autobús.", en: "You can take this bus." },
  { es: "Puede volver más tarde.", en: "You can come back later." },

  { es: "Podemos hablar en español.", en: "We can speak in Spanish." },
  { es: "Podemos vernos el jueves.", en: "We can meet on Thursday." },
  { es: "Podemos practicar otra vez.", en: "We can practice again." },
  { es: "Podemos pedir dos cafés.", en: "We can order two coffees." },
  { es: "Podemos hacerlo ahora mismo.", en: "We can do it right now." },
  { es: "Podemos terminar hoy.", en: "We can finish today." },

  { es: "Podéis sentaros al fondo.", en: "You all can sit in the back." },
  { es: "Podéis seguirme por aquí.", en: "You all can follow me this way." },
  { es: "Podéis pagar juntos o separados.", en: "You all can pay together or separately." },
  { es: "Podéis reservar por teléfono.", en: "You all can book by phone." },
  { es: "Podéis repetir la última parte.", en: "You all can repeat the last part." },

  { es: "Pueden pasar, por favor.", en: "You can come in, please." },
  { es: "Pueden esperar fuera.", en: "You can wait outside." },
  { es: "Pueden descargar la app.", en: "You can download the app." },
  { es: "Pueden elegir cualquier mesa.", en: "You can choose any table." },
  { es: "Pueden mandar los documentos hoy.", en: "You can send the documents today." },
  { es: "Pueden volver la semana que viene.", en: "You can come back next week." },
];
