export const PHRASES = [
  { es: "Ayer fui al supermercado después del trabajo.", en: "Yesterday I went to the supermarket after work." },
  { es: "Fui al médico por la mañana.", en: "I went to the doctor in the morning." },
  { es: "Fui a Madrid por un día.", en: "I went to Madrid for one day." },
  { es: "Fui en metro porque llovía.", en: "I went by metro because it was raining." },
  { es: "Fui a buscar a mi hermano al aeropuerto.", en: "I went to pick up my brother at the airport." },
  { es: "Fui al banco antes de comer.", en: "I went to the bank before eating." },
  { es: "Fui a casa y me dormí.", en: "I went home and fell asleep." },
  { es: "Fui al gimnasio a las siete.", en: "I went to the gym at seven." },
  { es: "Fui al concierto con unos amigos.", en: "I went to the concert with some friends." },
  { es: "Fui a preguntar por el curso.", en: "I went to ask about the course." },

  { es: "Tuve que salir temprano.", en: "I had to leave early." },
  { es: "Tuve una reunión larga.", en: "I had a long meeting." },
  { es: "Tuve un problema con la tarjeta.", en: "I had a problem with the card." },
  { es: "Tuve tiempo para leer en el tren.", en: "I had time to read on the train." },
  { es: "Tuve que cancelar la cita.", en: "I had to cancel the appointment." },
  { es: "Tuve suerte con el tráfico.", en: "I got lucky with traffic." },
  { es: "Tuve dolor de cabeza anoche.", en: "I had a headache last night." },
  { es: "Tuve que esperar media hora.", en: "I had to wait half an hour." },

  { es: "Hice la compra ayer.", en: "I did the grocery shopping yesterday." },
  { es: "Hice la cena para todos.", en: "I made dinner for everyone." },
  { es: "Hice una reserva por teléfono.", en: "I made a reservation by phone." },
  { es: "Hice ejercicio por la mañana.", en: "I exercised in the morning." },
  { es: "Hice una pregunta en clase.", en: "I asked a question in class." },
  { es: "Hice fotos en el viaje.", en: "I took photos on the trip." },
  { es: "Hice café para la oficina.", en: "I made coffee for the office." },
  { es: "Hice todo lo que pude.", en: "I did everything I could." },

  { es: "Pude llegar a tiempo.", en: "I was able to arrive on time." },
  { es: "Pude hablar con el profesor.", en: "I was able to speak with the teacher." },
  { es: "Pude cambiar la fecha.", en: "I was able to change the date." },
  { es: "Pude terminar el informe.", en: "I was able to finish the report." },
  { es: "Pude encontrar aparcamiento.", en: "I was able to find parking." },
  { es: "Pude descansar un poco.", en: "I was able to rest a little." },
  { es: "Pude resolver el problema.", en: "I was able to solve the problem." },

  { es: "Dije que sí.", en: "I said yes." },
  { es: "Dije la verdad.", en: "I told the truth." },
  { es: "Dije que llegaría tarde.", en: "I said I would be late." },
  { es: "Dije tu nombre mal, perdón.", en: "I said your name wrong, sorry." },
  { es: "Fue un día muy largo.", en: "It was a very long day." },
  { es: "Fue difícil al principio.", en: "It was difficult at first." },
  { es: "Fue más fácil de lo que pensé.", en: "It was easier than I thought." },
];
