export const PHRASES = [
  { es: "Madrid es grande.", en: "Madrid is big." },
  { es: "Este café es caro.", en: "This coffee is expensive." },
  { es: "Mi jefe es muy directo.", en: "My boss is very direct." },
  { es: "La reunión es corta.", en: "The meeting is short." },
  { es: "El examen es mañana.", en: "The exam is tomorrow." },
  { es: "Tu hermano es médico.", en: "Your brother is a doctor." },
  { es: "La sopa de aquí es muy buena.", en: "The soup here is very good." },
  { es: "Ese barrio es tranquilo.", en: "That neighborhood is calm." },
  { es: "El tren de las ocho es rápido.", en: "The eight o'clock train is fast." },
  { es: "La película es interesante.", en: "The movie is interesting." },

  { es: "Madrid está muy tranquila en agosto.", en: "Madrid is very quiet in August." },
  { es: "El café está cerrado ahora.", en: "The cafe is closed right now." },
  { es: "Mi jefe está en la oficina.", en: "My boss is in the office." },
  { es: "La reunión está en la sala dos.", en: "The meeting is in room two." },
  { es: "El examen está en la plataforma.", en: "The exam is on the platform." },
  { es: "Tu hermano está en urgencias.", en: "Your brother is in the emergency room." },
  { es: "La sopa está fría.", en: "The soup is cold." },
  { es: "Ese barrio está lejos del centro.", en: "That neighborhood is far from downtown." },
  { es: "El tren está lleno.", en: "The train is full." },
  { es: "La película ya está empezada.", en: "The movie has already started." },

  { es: "Estos taxis son caros.", en: "These taxis are expensive." },
  { es: "Mis vecinos son muy amables.", en: "My neighbors are very friendly." },
  { es: "Las tiendas de aquí son pequeñas.", en: "The shops here are small." },
  { es: "Tus hijos son muy altos.", en: "Your children are very tall." },
  { es: "Estos horarios son difíciles.", en: "These schedules are difficult." },
  { es: "Las clases son en línea.", en: "The classes are online." },
  { es: "Esos chicos son estudiantes.", en: "Those guys are students." },
  { es: "Las porciones son enormes.", en: "The portions are huge." },

  { es: "Los taxis están fuera.", en: "The taxis are outside." },
  { es: "Mis vecinos están de vacaciones.", en: "My neighbors are on vacation." },
  { es: "Las tiendas están cerradas hoy.", en: "The shops are closed today." },
  { es: "Tus hijos están en el parque.", en: "Your children are in the park." },
  { es: "Estos horarios están mal en la app.", en: "These schedules are wrong in the app." },
  { es: "Las clases están grabadas.", en: "The classes are recorded." },
  { es: "Esos chicos están en la biblioteca.", en: "Those guys are in the library." },
  { es: "Las porciones están listas.", en: "The portions are ready." },
];
