export const PHRASES = [
  { es: "Quiero que vengas temprano mañana.", en: "I want you to come early tomorrow." },
  { es: "Quiero que me llames cuando llegues.", en: "I want you to call me when you arrive." },
  { es: "Quiero que practiques esta frase diez veces.", en: "I want you to practice this sentence ten times." },
  { es: "Quiero que me digas la verdad.", en: "I want you to tell me the truth." },
  { es: "Quiero que reservemos una mesa cerca de la ventana.", en: "I want us to reserve a table near the window." },
  { es: "Quiero que pidamos en español.", en: "I want us to order in Spanish." },
  { es: "Quiero que tomes agua.", en: "I want you to drink water." },
  { es: "Quiero que salgas con tiempo.", en: "I want you to leave with enough time." },
  { es: "Quiero que estés aquí a las ocho.", en: "I want you to be here at eight." },
  { es: "Quiero que busquéis la dirección en el mapa.", en: "I want you all to look up the address on the map." },
  { es: "Quiero que me enviéis el archivo hoy.", en: "I want you all to send me the file today." },
  { es: "Quiero que ellos lleguen antes de las nueve.", en: "I want them to arrive before nine." },

  { es: "Es importante que descanses.", en: "It is important that you rest." },
  { es: "Es importante que uses auriculares.", en: "It is important that you use headphones." },
  { es: "Es importante que traigas el pasaporte.", en: "It is important that you bring the passport." },
  { es: "Es importante que no llegues tarde.", en: "It is important that you do not arrive late." },
  { es: "Es importante que estemos listos.", en: "It is important that we be ready." },
  { es: "Es importante que tengan efectivo.", en: "It is important that they have cash." },
  { es: "Es importante que pidáis ayuda si no entendéis.", en: "It is important that you all ask for help if you do not understand." },
  { es: "Es importante que yo practique cada día.", en: "It is important that I practice every day." },

  { es: "Ojalá que no llueva mañana.", en: "I hope it does not rain tomorrow." },
  { es: "Ojalá que podamos salir temprano.", en: "I hope we can leave early." },
  { es: "Espero que estés bien.", en: "I hope you are well." },
  { es: "Espero que te guste esta clase.", en: "I hope you like this class." },
  { es: "Espero que encuentres el museo.", en: "I hope you find the museum." },
  { es: "Espero que os guste el barrio.", en: "I hope you all like the neighborhood." },
  { es: "Te llamo para que sepas el plan.", en: "I am calling you so that you know the plan." },
  { es: "Te escribo para que no te olvides.", en: "I am writing to you so that you do not forget." },
  { es: "Hablo despacio para que me entiendas.", en: "I speak slowly so that you understand me." },
  { es: "Repito la frase para que la oigas bien.", en: "I repeat the sentence so that you hear it well." },
  { es: "Les mando la ubicación para que lleguen fácil.", en: "I send them the location so that they arrive easily." },
  { es: "Compro pan ahora para que cenemos antes.", en: "I buy bread now so that we have dinner earlier." },
];
