export const PHRASES = [
  { es: "Tengo que salir temprano mañana.", en: "I have to leave early tomorrow." },
  { es: "Tengo que llamar al banco antes de las tres.", en: "I have to call the bank before three." },
  { es: "Tengo que enviar este correo hoy.", en: "I have to send this email today." },
  { es: "Tengo que pagar el alquiler el lunes.", en: "I have to pay the rent on Monday." },
  { es: "Tengo que recoger a mi hija a las cinco.", en: "I have to pick up my daughter at five." },
  { es: "Tengo que pasar por la farmacia después del trabajo.", en: "I have to stop by the pharmacy after work." },
  { es: "Tengo que terminar este informe esta noche.", en: "I have to finish this report tonight." },
  { es: "Tengo que cambiar la cita con el dentista.", en: "I have to change the dentist appointment." },
  { es: "Tengo que llevar el coche al taller.", en: "I have to take the car to the mechanic." },
  { es: "Tengo que comprar pan de camino a casa.", en: "I have to buy bread on the way home." },

  { es: "Tienes que bajar en la próxima parada.", en: "You have to get off at the next stop." },
  { es: "Tienes que traer tu pasaporte al aeropuerto.", en: "You have to bring your passport to the airport." },
  { es: "Tienes que contestar a ese mensaje.", en: "You have to answer that message." },
  { es: "Tienes que probar esta sopa.", en: "You have to try this soup." },
  { es: "Tienes que guardar este número.", en: "You have to save this number." },
  { es: "Tienes que salir ya o perderás el tren.", en: "You have to leave now or you will miss the train." },
  { es: "Tienes que descansar más.", en: "You have to rest more." },

  { es: "Tiene que firmar aquí, por favor.", en: "You have to sign here, please." },
  { es: "Tiene que esperar un momento.", en: "You have to wait a moment." },
  { es: "Tiene que tomar este medicamento con comida.", en: "You have to take this medicine with food." },
  { es: "Tiene que renovar su tarjeta esta semana.", en: "You have to renew your card this week." },
  { es: "Tiene que hablar con recursos humanos.", en: "You have to speak with human resources." },
  { es: "Tiene que volver mañana.", en: "You have to come back tomorrow." },
  { es: "Tiene que pedir turno en la app.", en: "You have to book a slot in the app." },

  { es: "Tenemos que ir al supermercado.", en: "We have to go to the supermarket." },
  { es: "Tenemos que reservar mesa para ocho.", en: "We have to reserve a table for eight." },
  { es: "Tenemos que revisar el contrato.", en: "We have to review the contract." },
  { es: "Tenemos que llegar media hora antes.", en: "We have to arrive half an hour early." },
  { es: "Tenemos que buscar otro piso.", en: "We have to look for another apartment." },
  { es: "Tenemos que practicar todos los días.", en: "We have to practice every day." },
  { es: "Tenemos que ahorrar para el viaje.", en: "We have to save for the trip." },

  { es: "Tenéis que traer ropa cómoda.", en: "You all have to bring comfortable clothes." },
  { es: "Tenéis que confirmar la reserva hoy.", en: "You all have to confirm the reservation today." },
  { es: "Tenéis que estudiar estos verbos.", en: "You all have to study these verbs." },
  { es: "Tenéis que llamar a vuestros padres.", en: "You all have to call your parents." },
  { es: "Tenéis que salir por esta puerta.", en: "You all have to leave through this door." },
  { es: "Tenéis que decidir ahora.", en: "You all have to decide now." },

  { es: "Tienen que entregar el proyecto el viernes.", en: "They have to hand in the project on Friday." },
  { es: "Tienen que subir por las escaleras.", en: "They have to go up the stairs." },
  { es: "Tienen que pedir cita previa.", en: "They have to request an appointment." },
  { es: "Tienen que apagar el móvil en clase.", en: "They have to turn off their phone in class." },
  { es: "Tienen que revisar los resultados.", en: "They have to check the results." },
  { es: "Tienen que esperar fuera.", en: "They have to wait outside." },
  { es: "Tienen que volver antes de medianoche.", en: "They have to come back before midnight." },
];
